language: python
python:
- '2.7'

install:
  - source devtools/travis-ci/install.sh
script:
- nosetests -v deepchem

env:
  global:
  # encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push documentation to S3
  - secure: "phb7WC1IFAY2UkANd0ydiME/Abt9g73DcqkIrjt5I9UMG3gqMXtZ5wn2X3eolZQdmHVG/1ZheEf+XX1F1+12c3FlD2kVQWkpuOBAJMzjlqe7KwrAclFopqQa5Lro4kH5gAz5GOkXuaWY9CmL/WObOCnVq3MKmbJRO3jTnLU5OxD/ecbfZUZXFQsWegp5A/DiYjG7BjBqD90BCNKNGGd8ALZDEojOu0wJQuwm/1pG4CjgT79ji4S+ygnjnA3/bJf+j1gzTo5naJyqHPITO1N71uQlb9ZZmUhzLveRu2tANSAPyxnUUI6daTpRRQUKof75QggnPbGPsj+IF/DL69YOeTXAVeTT4Stt9k6gWjTPCVQOb36fkMbYNMKaIN4L33WBsXJXqxJ5i9LXMCMoeCYB92p56q2Wp5TvhS2SgRX+rLmZCd29dN7aN31X61XsjKImr846DyABnlinZ2faUG5HNa2tOEm1xuHatW8UGMNHBkhR0rUMIlZaVYv7kQtbH8uGRwsRQH326pmMmQJwLkVe9l78cScN/C7ETvPimCBZEwjiw0shNelao52z39JlLKSvuPll172dbubb5aEls/1+uAWsQ05KnjtUlMBsARtRv99RVKDvsNUqlTAjQbWDj82JktLf+FATSAZ7s5Sj9yLWKD+QiO3Ug8JNpf6+ezm8mBo="
  - secure: "Qu0HJwAAzxcavXcDn7mIczNc3sv3xZNYs0LPoCEsJ4azjewFAC9KwI9tptqdbnEkcRJ3cyHde2n+CLg67+m3KTg9s6hoJ+lUSb+jW97zSVXusF4p3vprak+i2dqnH8JAwMD2mOktmSC+FKsQEUzm0gwwCg1BPzxJTsTngWKjYqRk5aAddSMGrVojV+D3mQoyZhqI+eCg7YRb3bl43aPwrcy11yDLhmEbP/8zEuabu02IG3Eix7qJghALbTaRi2amNSmS900y70Jm6uvIX+cUnkXJImUQathwrbIUJfQLTTQN6Rs5prR5MRd2a9Dtcp1ZtnQykNpfZ6bn847jdDtBx3emovvj4CQMEoxhTSUgePjYhU3rU7lVa5tIt2ZITL638MnZUHXVj36bZXzYJpmKZK9tUFQAp7RdjCf8twdfxaQYaVj6buZrJtD0EYDCyLtSA2KHkY48Z6+8z6idxL3vPACnuREsBpRc9I/oyJ9ygrXR9ghUdS0Pt+0YQwzkBvW3dREDdQL/ibWoI3WTXEY0y7TO/LfAAkk51MBE79xdq4EilzVrMEzGlsihPI6dGbYvF2V8+jBGN1XPayHPFIL4QBJuCo1sk7lXf55siAyMElq1uTmKTF3qn1BXs7p8DSyQQ5+S/CeWokOPNYZTpvWgM0B/BvMt2wJwcVQoOtlQM9o="

after_success:
  - source devtools/travis-ci/after_sucess.sh
