language: python
python:
- '2.7'
- '3.5'
sudo: required
dist: trusty
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/archive/Anaconda2-4.2.0-Linux-x86_64.sh
  -O anaconda.sh; else wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
  -O anaconda.sh; fi
- bash anaconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --add channels http://conda.binstar.org/omnia
- conda install pandas
- conda install -c omnia rdkit
- conda install -c omnia boost=1.59.0
- conda install -c omnia openbabel
- conda install joblib
- conda install h5py
- pip install keras
- export KERAS_BACKEND=tensorflow
- conda install seaborn
- conda install six
- conda install dill
- conda install runipy
- conda install ipyparallel
- pip install runipy
- pip install nglview
- conda install -c omnia mdtraj
- python setup.py install
- conda install -c https://conda.anaconda.org/jjhelmus tensorflow
script:
- nosetests -v deepchem --nologcapture
after_success:
- source devtools/travis-ci/after_sucess.sh
env:
  global:
  - secure: FojR+Zrw/XLeDWHaZnwqkBt7DGwOJ6N9X0HJIkkzGsTxQy405qY9bfKMgzivY4UAppqWH2R9kcY/3K2lnFOU9Z2dSf9ZSLVmXjQQK+YhiFiPVQG1bQ8XEhQ51927AZn2wGqzPSFlOI8M4ek2V4a6d72Wg6SOooVbI+A9PtrdXNJlEfonY0QfSakhg+IFPBsN84khbGaHlTRCXvozRTSm3Ubo4jidN54WbO7Ll18qJ183Fgh8SVxYfodDAusZaWU2e/q9lCk6nkJ9bDC9anPbuTXpSlIkH7x7WcrMbLCrvvHJq26YOCjReCDea1/N8ECsarXWfvPjz1Cv59QSghoLxFeRRNCDHWaWTccKgWRAFd60+vSgd8CcoMFsMY0XedO2mSQztLAb2pS2TCoCPMD/5Zip5pkXOxJB5CwPqSuJ41FBPYthzyhG1MPbaQnPDZjtx5TDaVdN5w+Nfc40i9+0rFNisEyAdi2dTcr6bWZ7UlWj7LBDJGVjYPC8lKsaip6dyov3KeLveod0IbY5zCVnqF2rwuID5n/6ejGgytv1caZWa9TvEjzuSJoo8d2uXwyTzQLntardt2ZvtA8ZmwChyaq0pNtUgxQE4wn8hZG19+lAvIc95ZDJuSV7xwuo5XsMDffa3jrjyWhByveyfbHs1znAmAl4w6NJ32ylWr0/+Do=
  - secure: JDldUkMQE7+vlKX2ghTFhGWCWHzJJtC4w8xIzAaKo04zHaBcrHSmhXXwkkPjyGjgcXE6ORKUI/zJnCecErpPbHYVEQUGzyTG9ikQr0pIENTua5j5AHJUt5Y+aWsD2fzNWE1ZT88sxKAqj96rsfRfj7coymkoyLXrvqdd5OVm+sEiup5MLGEutbMrOPXChSXBUiGetLakoMnQ0WznOttWVUb52j5SsCJSOh7baX0eNdEmaGZ+ok4R/j8/c8LTARVOC2AZ6c6BIfJPHk7rPpq4HoeVRIgp2o7vbjosE+eI499OPP1AcFHUm38XJ68mDsw5exu/ONEbFgxzA2hXqVW/TDnWpaJ0hLKxjGg8JnJ63OYWyY2nk7UGQNPwiVj4DiN7zsNkV1+IbaUmiGjbWAxyCa8FBOoXos7DQ7pVtWNvhZtsAzJaCNgvCFgsrxcutxGuN9zkpmL30QNpE6HT/mvmww5MHH5KacBYPLjqmihQCuasT9L6k2+dPspRRfbrgyBZJxffteWumXBThIaqs8BuqG1CxxgkOgvUTSBZyoZtfX3CW8ClEIKT89+bQXQKwcqSqWCu7qsFx7A6ssmzliCzO5iXZhxaPS7rICqRu4HPJ1YNS5bUbwwEmBeMw0ATsxpfo0ityNSJbO0AvXiIr9fcVv0cPJuz3pialFrGDMMPjeY=
  matrix:
  - secure: S5rANCGbsMsvoze8B4Xrcp25wdnigZAgD1uHinKuksvFZAJo5To04k8k7iUqi7+sYtiNKWQV5werICcJ6+gaNxb58+RB4AV8O+/Pa8SvM/FxSbITLC35QhQKt12wXy2J4JXBFLe9kYcCWdojweu+IDM4Uy7WqTdZ5oE/za6HxNLIyxAV4SViddwotK0fg628KqyJBiY+foGodLB/8EVrxYjxMQq5nnJA5wC97grWEPP/zCL+lsaEjjcVnyUWUWztlCvzNGneVx38Wvwi5oF12HbssdOVtIcoUF+RDwx9BFBgdK7zSGhmS8j3Lqz3V6+KqZsHB8gvm2tOhZCtDOhTWDKJc30X69i1XgQgcKBnlkOvOVtjp3xuGC0/jyc3SE97slRDkpnGSiN7LWTHGp65uQNigAD5sXWU8DJe6HbeVioTE//e4TKxLKSytrDaRqQvSjlbrDdGrmvsSrlstOjXJ48P/ntQz311lEujwXmInTokrJ7+WLuCtIMV8qLPPToNZsWsUMLQYO9UUJYFXobDz5VZNhD1VCMkZ/zMOA3yLfB7U1gfYk0C+K+b/PAx1DJEbv1X+ASYkR/2uBvQ03oaLNQGOnDSWNr9MR6j2uW/EygZ2Zl8in9dw/K+4A3Zu5FfH3wkqiKbXTD8b9CUa79Gaa7Pj9iG+BIpGJ0+GgqxaQY=
  - secure: sRF47ac0M7O9fcSJGuM/+ravkSOvGBfuvMwsRWkpwyGIvkXJKG5jWhKjD8E3b5Q8ZtqetB5DlMszbpBpnBLky+eBdhK4ZYQs2Ph9Fk3KyFvfkHLfumlXctpVoNu/dQMqq4IK7rUOGvnEi2Fc2QTZIobjqM5wG0x5IIksKFWyBC2XNGXYktT4Dl0N1ni2Fu66mp6s+iLUBeGwse+5L9Be7OM8hUsnZnV/loRhHhie/6gSQEBiysF4jYlxNplKFxQq/bAEV3fnjYo4t/XYR2wXLe/YtciqRKBsM0e96rl2/SEw7YApFYLUPwg3O5uCp4lOuJNC16iIt2B5WuknAabMWzKwAPydvJnRZuSN7qZPlM+wIsDIqk+mqkD57FxFZmxK55S6LQFOdgA2PQVFLI51sevajPIEYo/nSS0Cu9/AN5Rr1mRwhRjiw+8Wc2SUeb4X7yJagjJG4KPh6nF4eKZiL4I+CBBz5lZ3afgIgryVWofWCHu2PTqR/F8R63CzY0q5pEUQ2AEQWPaZM3q8LlwoIDWmWF1JO/JBHIVamOKKAcN5avoZxSaMsnVjAi9B7lmsPxLFLeZjWpt3mythc05suS44EbnjUY+IlETlj3bccB3P/6g98dQi4PsDruq13Xh133ZvRlgozw0wQypoBC4tWyJsgSprg3CeAkWHrFFxluo=
