name: deepchem
channels:
  - deepchem
  - omnia
  - conda-forge
  - defaults
dependencies:
  - openmm
  - pdbfixer
  - rdkit
  - simdna
  - pip
  - pip:
    - biopython
    - matminer
    - mdtraj
    - networkx
    - pillow
    - pyGPGO
    - pymatgen
    - xgboost
