name: deepchem
channels:
  - deepchem
  - omnia
  - conda-forge
  - defaults
dependencies:
  - openmm==7.4.2
  - pdbfixer==1.6
  - rdkit==2020.03.4
  - simdna==0.4.3.2
  - pip
  - pip:
    - biopython==1.77
    - matminer==0.6.3
    - mdtraj==1.9.4
    - networkx==2.4
    - pillow==7.1.2
    - pyGPGO==0.4.0.dev1
    - pymatgen==2020.7.18
    - tensorflow==2.2.0
    - tensorflow-probability==0.10.1
    - torch==1.5.1
    - torch-cluster==1.5.6
    - torch-geometric==1.6.0
    - torch-scatter==2.0.5
    - torch-sparse==0.6.6
    - torch-spline-conv==1.2.0
    - xgboost==1.1.1
    - pytest
    - pytest-cov
    - flaky
